version: '3'

services:
  app:
    build: .
    command: node ace serve --watch
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: prova_adonis
